#!/usr/bin/env python
"""
evaluate.py
===========
Loads trained checkpoints (``checkpoints/realnvp.pt``, ``checkpoints/diffusion.pt``),
draws samples from ``p_model(X_{t+Delta t} | X_t)`` conditioned on the held-out
validation states, and computes the benchmark metrics: Wasserstein distance,
KL divergence, Hellinger distance, MMD, sampling speed, training time, GPU
memory, and (for the flow) exact negative log-likelihood.

Exposes reusable functions consumed by ``compare.py``; also runnable directly
to evaluate + print a single model's numbers:

    python evaluate.py --model nf
    python evaluate.py --model diffusion
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Callable, Optional

import numpy as np
import torch

from config import Config, add_config_arguments, build_config
from dataset import Normalizer, load_splits
from metrics import compute_all_distribution_metrics, flow_negative_log_likelihood
from models.diffusion import ConditionalDenoiser, GaussianDiffusion
from models.realnvp import ConditionalRealNVP
from utils import Timer, get_device, load_checkpoint


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------
def load_flow(cfg: Config, device: torch.device):
    path = os.path.join(cfg.checkpoint_dir, "realnvp.pt")
    ck = load_checkpoint(path, map_location=device)
    model = ConditionalRealNVP(**ck["model_config"]).to(device)
    model.load_state_dict(ck["model_state_dict"])
    model.eval()
    x_norm = Normalizer.from_dict(ck["x_norm"])
    y_norm = Normalizer.from_dict(ck["y_norm"])
    return model, x_norm, y_norm, ck


def load_diffusion(cfg: Config, device: torch.device, use_ema: bool = True):
    path = os.path.join(cfg.checkpoint_dir, "diffusion.pt")
    ck = load_checkpoint(path, map_location=device)
    mc = ck["model_config"]
    denoiser = ConditionalDenoiser(
        data_dim=mc["data_dim"], cond_dim=mc["cond_dim"], hidden_dim=mc["hidden_dim"],
        n_res_blocks=mc["n_res_blocks"], time_embed_dim=mc["time_embed_dim"],
        cond_embed_dim=mc["cond_embed_dim"],
    )
    diffusion = GaussianDiffusion(
        denoiser, n_timesteps=mc["n_timesteps"], schedule=mc["schedule"],
        parameterization=mc.get("parameterization", "eps"), sampler=mc.get("sampler", "ancestral"),
        ddim_steps=mc.get("ddim_steps", 50), ddim_eta=mc.get("ddim_eta", 0.0),
    ).to(device)
    state = ck["ema_state_dict"] if use_ema else ck["model_state_dict"]
    diffusion.load_state_dict(state)
    diffusion.eval()
    x_norm = Normalizer.from_dict(ck["x_norm"])
    y_norm = Normalizer.from_dict(ck["y_norm"])
    return diffusion, x_norm, y_norm, ck


# ---------------------------------------------------------------------------
# Raw-space sampling helpers (take/return unnormalised numpy arrays)
# ---------------------------------------------------------------------------
@torch.no_grad()
def sample_flow_raw(model: ConditionalRealNVP, x_raw: np.ndarray, x_norm: Normalizer,
                     y_norm: Normalizer, device: torch.device, batch_size: int = 20000) -> np.ndarray:
    x_raw = np.asarray(x_raw, dtype=np.float32).reshape(-1, 1)
    outs = []
    for i in range(0, len(x_raw), batch_size):
        chunk = x_raw[i:i + batch_size]
        xn = x_norm.transform(chunk).astype(np.float32)
        xt = torch.from_numpy(xn).to(device)
        yn = model.sample(xt).cpu().numpy()
        outs.append(y_norm.inverse(yn).ravel())
    return np.concatenate(outs)


@torch.no_grad()
def sample_diffusion_raw(diffusion: GaussianDiffusion, x_raw: np.ndarray, x_norm: Normalizer,
                          y_norm: Normalizer, device: torch.device,
                          batch_size: int = 20000) -> np.ndarray:
    x_raw = np.asarray(x_raw, dtype=np.float32).reshape(-1, 1)
    dim = y_norm.mean.shape[-1]
    outs = []
    for i in range(0, len(x_raw), batch_size):
        chunk = x_raw[i:i + batch_size]
        xn = x_norm.transform(chunk).astype(np.float32)
        xt = torch.from_numpy(xn).to(device)
        yn = diffusion.sample(xt, dim=dim).cpu().numpy()
        outs.append(y_norm.inverse(yn).ravel())
    return np.concatenate(outs)


def timed_sample(sample_fn: Callable[[np.ndarray], np.ndarray], x_raw: np.ndarray):
    with Timer() as t:
        samples = sample_fn(x_raw)
    rate = len(x_raw) / max(t.elapsed, 1e-9)
    return samples, t.elapsed, rate


# ---------------------------------------------------------------------------
# Empirical exit (absorbing-boundary) model, built from data_exit.npz if present
# ---------------------------------------------------------------------------
class EmpiricalExitModel:
    """Bins X_t and looks up the empirical P(exit during one step | X_t) from
    ``data_exit.npz`` (already generated by ``data_generation.py`` -- not
    regenerated here). Used only to make the multi-step rollout comparison
    fair across Ground Truth / NF / Diffusion, none of which model the exit
    event themselves (like the flow map in ``jump1d``, they only learn the
    survivor-to-survivor transition kernel)."""

    def __init__(self, x: np.ndarray, exited: np.ndarray, nbins: int = 40):
        lo, hi = float(x.min()), float(x.max())
        self.edges = np.linspace(lo, hi, nbins + 1)
        idx = np.clip(np.digitize(x, self.edges) - 1, 0, nbins - 1)
        self.prob = np.zeros(nbins)
        for b in range(nbins):
            m = idx == b
            self.prob[b] = exited[m].mean() if m.sum() > 0 else 0.0

    def exit_prob(self, x_query: np.ndarray) -> np.ndarray:
        idx = np.clip(np.digitize(x_query, self.edges) - 1, 0, len(self.prob) - 1)
        return self.prob[idx]

    def sample_exit(self, x_query: np.ndarray, rng: np.random.Generator) -> np.ndarray:
        return rng.random(len(x_query)) < self.exit_prob(x_query)


def load_exit_model(cfg: Config) -> Optional[EmpiricalExitModel]:
    path = os.path.join(os.path.dirname(cfg.data_path), "data_exit.npz")
    if not os.path.exists(path):
        return None
    d = np.load(path)
    return EmpiricalExitModel(d["x"], d["exited"])


# ---------------------------------------------------------------------------
# Non-parametric nearest-neighbour bootstrap: a Ground-Truth transition
# sampler built directly from the (already generated) data pairs, so the
# "Ground Truth" curve in figures 1-9 is not limited to the exact X_t values
# present in the validation split.
# ---------------------------------------------------------------------------
class NearestNeighborTransitionSampler:
    def __init__(self, x_train: np.ndarray, y_train: np.ndarray, k: int = 64, seed: int = 0):
        order = np.argsort(x_train.ravel())
        self.xs = x_train.ravel()[order]
        self.ys = y_train.ravel()[order]
        self.k = min(k, len(self.xs))
        self.rng = np.random.default_rng(seed)

    def sample(self, x_query: np.ndarray) -> np.ndarray:
        x_query = np.asarray(x_query).ravel()
        center = np.clip(np.searchsorted(self.xs, x_query), 0, len(self.xs) - 1)
        lo = np.clip(center - self.k // 2, 0, len(self.xs) - self.k)
        offsets = self.rng.integers(0, self.k, size=len(x_query))
        return self.ys[lo + offsets]


# ---------------------------------------------------------------------------
# Metric bundle for one model against ground truth
# ---------------------------------------------------------------------------
def evaluate_model(model_type: str, cfg: Config, device: torch.device) -> dict:
    """Full metric bundle for ``model_type in {"nf", "diffusion"}``."""
    (x_train, y_train, x_val, y_val), _ = load_splits(cfg)

    if model_type == "nf":
        model, x_norm, y_norm, ck = load_flow(cfg, device)
        sample_fn = lambda xr: sample_flow_raw(model, xr, x_norm, y_norm, device)
        xt = torch.from_numpy(x_norm.transform(x_val).astype(np.float32)).to(device)
        yt = torch.from_numpy(y_norm.transform(y_val).astype(np.float32)).to(device)
        nll = flow_negative_log_likelihood(model, yt, xt)
        display_name = "Conditional RealNVP"
    elif model_type == "diffusion":
        model, x_norm, y_norm, ck = load_diffusion(cfg, device)
        sample_fn = lambda xr: sample_diffusion_raw(model, xr, x_norm, y_norm, device)
        nll = None
        display_name = "Conditional DDPM"
    else:
        raise ValueError(f"unknown model_type {model_type!r}")

    # paired samples: one ML draw per validation X_t -> comparable marginals
    gen_val, sample_time_s, sample_rate = timed_sample(sample_fn, x_val)
    dist_metrics = compute_all_distribution_metrics(y_val, gen_val)

    result = {
        "model": display_name,
        "model_type": model_type,
        **dist_metrics,
        "nll": nll,
        "sampling_time_s": sample_time_s,
        "sampling_rate_samples_per_s": sample_rate,
        "training_time_s": ck["training_time_s"],
        "peak_gpu_mem_bytes": ck["peak_gpu_mem_bytes"],
        "history": ck["history"],
        "y_val": y_val,
        "gen_val_samples": gen_val,
    }
    return result


def evaluate_anchors(cfg: Config, device: torch.device) -> list:
    """Conditional density slices at a few representative X_t anchors, used
    for the histogram/PDF-overlay/QQ/CDF figures."""
    (x_train, y_train, x_val, y_val), _ = load_splits(cfg)
    flow, xn_f, yn_f, _ = load_flow(cfg, device)
    diffusion, xn_d, yn_d, _ = load_diffusion(cfg, device)

    quantiles = np.linspace(0.1, 0.9, cfg.eval_n_anchors)
    anchors = np.quantile(x_val.ravel(), quantiles)

    slices = []
    for anchor in anchors:
        mask = np.abs(x_val.ravel() - anchor) <= cfg.eval_anchor_tolerance
        gt_slice = y_val.ravel()[mask]
        if len(gt_slice) < 20:
            continue
        n = min(len(gt_slice), cfg.eval_n_samples)
        x_repeat = np.full(n, anchor, dtype=np.float32)
        nf_samples = sample_flow_raw(flow, x_repeat, xn_f, yn_f, device)
        diff_samples = sample_diffusion_raw(diffusion, x_repeat, xn_d, yn_d, device)
        slices.append({
            "anchor": float(anchor),
            "gt": gt_slice[:n],
            "nf": nf_samples,
            "diffusion": diff_samples,
        })
    return slices


def evaluate_rollout(cfg: Config, device: torch.device) -> dict:
    """Multi-step rollout comparison: Ground Truth (NN-bootstrap + empirical
    exit model) vs. NF vs. Diffusion, each composed ``cfg.rollout_steps`` times."""
    (x_train, y_train, x_val, y_val), _ = load_splits(cfg)
    flow, xn_f, yn_f, _ = load_flow(cfg, device)
    diffusion, xn_d, yn_d, _ = load_diffusion(cfg, device)
    exit_model = load_exit_model(cfg)
    nn_sampler = NearestNeighborTransitionSampler(x_train, y_train, seed=cfg.seed)

    lo, hi = float(x_train.min()), float(x_train.max())
    rng = np.random.default_rng(cfg.seed + 7)
    x0 = rng.uniform(lo, hi, size=cfg.rollout_n_particles).astype(np.float32)

    step_fns = {
        "ground_truth": lambda xr: nn_sampler.sample(xr),
        "nf": lambda xr: sample_flow_raw(flow, xr, xn_f, yn_f, device),
        "diffusion": lambda xr: sample_diffusion_raw(diffusion, xr, xn_d, yn_d, device),
    }

    out = {}
    for name, step_fn in step_fns.items():
        x = x0.copy()
        alive = np.ones(len(x), dtype=bool)
        survival = []
        for _ in range(cfg.rollout_steps):
            idx = np.where(alive)[0]
            if len(idx) == 0:
                survival.append(0.0)
                continue
            if exit_model is not None:
                exited = exit_model.sample_exit(x[idx], rng)
                alive[idx[exited]] = False
                idx = idx[~exited]
            if len(idx):
                xn = step_fn(x[idx])
                oob = (xn < lo) | (xn > hi)
                alive[idx[oob]] = False
                x[idx[~oob]] = xn[~oob]
            survival.append(float(alive.mean()))
        out[name] = {"terminal": x[alive], "survival": survival}
    return out


# ---------------------------------------------------------------------------
# Standalone CLI
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a single trained model.")
    parser.add_argument("--model", choices=["nf", "diffusion"], required=True)
    add_config_arguments(parser)
    args = parser.parse_args()
    cfg = build_config(args)

    device = get_device(cfg)
    result = evaluate_model(args.model, cfg, device)
    skip = {"history", "y_val", "gen_val_samples"}
    printable = {k: v for k, v in result.items() if k not in skip}
    print(json.dumps(printable, indent=2, default=float))

    out_path = os.path.join(cfg.results_dir, f"{args.model}_eval.json")
    with open(out_path, "w") as f:
        json.dump(printable, f, indent=2, default=float)
    print(f"[evaluate] wrote {out_path}")


if __name__ == "__main__":
    main()
