"""
07_train_network.py
===================
PURPOSE
-------
Train a neural network G(x, z) → ΔX that approximates the label mapping
generated in script 06.

At rollout time (script 08):
    z ~ N(0,1)
    ΔX = G(x_t, z)     ← fast, ~microseconds per evaluation
    x_new = x_t + ΔX

THE NETWORK ARCHITECTURE
-------------------------
We use a simple MLP (Multi-Layer Perceptron) with:
    Input:  [x_t, z]            (2-dimensional)
    Hidden: [256, 256, 256, 256]  (4 hidden layers, ReLU activation)
    Output: [ΔX]                (1-dimensional)

WHY MLP AND NOT SOMETHING FANCIER?
------------------------------------
1. The input is only 2-D (x_t, z) — no need for attention or convolutions.
2. The target function ΔX ≈ μ(x) + σ(x)·z is smooth and Lipschitz.
3. MLPs with ReLU can approximate any smooth function (universal approximation).
4. Simple = easy to understand and debug.

LOSS FUNCTION: MSE
-------------------
L(θ) = E[(G_θ(x_t, z) - ΔX_label)²]

We minimize this over all training pairs (x_t, z, ΔX_label) from script 06.

WHY MSE AND NOT MAXIMUM LIKELIHOOD?
-------------------------------------
We are learning a DETERMINISTIC FUNCTION (x,z) → ΔX.
For a fixed z, G(x,z) outputs ONE value of ΔX.
The randomness comes from sampling z ~ N(0,1) at rollout time.

MSE minimises the expected squared error between our prediction and the
label.  Since our labels are "exact" (generated by the bijection from
script 06), MSE converges to the true label function.

If we trained with NLL instead, we would need a probabilistic output head,
which adds complexity without benefit here.

KEY INSIGHT: THE NETWORK LEARNS THE BOUNDARY EFFECT
------------------------------------------------------
For x_t deep in the interior (say x_t = 3.0):
    z=0   →  ΔX ≈ μ(3.0) ≈ 0          (no drift)
    z=1   →  ΔX ≈ σ(3.0) ≈ 0.022      (one std up)
    z=-1  →  ΔX ≈ -σ(3.0) ≈ -0.022    (one std down)
    (symmetric)

For x_t near the left wall (say x_t = 0.05):
    z=0   →  ΔX ≈ μ(0.05) > 0         (drift AWAY from wall)
    z=1   →  ΔX ≈ small positive       (still away from wall)
    z=-3  →  ΔX ≈ small positive       (even large negative z maps to a
                                        tiny increment because the label
                                        clipped the distribution)
    (asymmetric — the BOUNDARY EFFECT)

The network LEARNS this asymmetry from the labels, not from any explicit
boundary condition.  This is what makes the method work.

OUTPUT
------
models/flow_model.pt       — trained network weights
plots/training_loss.png    — training and validation loss curves
plots/prediction_examples.png — predicted vs true ΔX at several x values
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from tqdm import tqdm

import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader, random_split

import config
import utils
from model import FlowNet

# ---------------------------------------------------------------------------
# 0.  Setup
# ---------------------------------------------------------------------------
config.ensure_dirs()
torch.manual_seed(config.SEED)
np.random.seed(config.SEED)

device = torch.device("cpu")   # MPS or CUDA if available
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
print(f"Using device: {device}")

print("=" * 60)
print("STEP 07 — Train Neural Network G(x, z) → ΔX")
print("=" * 60)
print()

# ---------------------------------------------------------------------------
# 1.  Load labels
# ---------------------------------------------------------------------------
print("Loading labels …")
lab   = np.load(os.path.join(config.DATA_DIR, "labels.npz"))
x_t   = lab["x_t"].astype(np.float32)
z     = lab["z"].astype(np.float32)
dx    = lab["dx"].astype(np.float32)
mu_x  = lab["mu_x"].astype(np.float32)
sig_x = lab["sig_x"].astype(np.float32)

print(f"  Total labels: {len(x_t):,}")
utils.print_stats("x_t", x_t)
utils.print_stats("z",   z)
utils.print_stats("dx",  dx)
print()

# ---------------------------------------------------------------------------
# 2.  Build PyTorch Dataset
# ---------------------------------------------------------------------------
#
# Input features: we concatenate (x_t, z) into a 2-D vector.
# Target:         dx  (the increment ΔX)
#
# We also normalise x_t to [0,1] by dividing by DOMAIN_HI.
# This helps the network converge faster.
#
x_norm = torch.tensor(x_t / config.DOMAIN_HI, dtype=torch.float32)   # → [0, 1]
z_tens = torch.tensor(z,  dtype=torch.float32)
y_tens = torch.tensor(dx, dtype=torch.float32)

# Stack inputs into a (N, 2) matrix
X_in = torch.stack([x_norm, z_tens], dim=1)   # shape (N, 2)
Y_in = y_tens.unsqueeze(1)                    # shape (N, 1)

dataset = TensorDataset(X_in, Y_in)

# 80/20 train/val split
n_train = int(0.8 * len(dataset))
n_val   = len(dataset) - n_train
train_ds, val_ds = random_split(dataset, [n_train, n_val],
                                 generator=torch.Generator().manual_seed(config.SEED))

train_loader = DataLoader(train_ds, batch_size=config.BATCH_SIZE, shuffle=True,
                           num_workers=0, pin_memory=False)
val_loader   = DataLoader(val_ds,   batch_size=config.BATCH_SIZE * 4, shuffle=False,
                           num_workers=0, pin_memory=False)

print(f"  Training samples  : {n_train:,}")
print(f"  Validation samples: {n_val:,}")
print(f"  Batch size        : {config.BATCH_SIZE}")
print(f"  Batches per epoch : {len(train_loader)}")
print()

# ---------------------------------------------------------------------------
# 3.  Instantiate network (defined in model.py)
# ---------------------------------------------------------------------------
# FlowNet is imported at the top of this script from model.py.
# That file is the single source of truth for the architecture so that
# scripts 08+ can load the same network without re-running training.

model = FlowNet().to(device)

# Count parameters
n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Network architecture:")
print(f"  Input dim   : 2  (x_t_normalised, z)")
print(f"  Hidden dim  : {config.HIDDEN_DIM}")
print(f"  Layers      : {config.N_LAYERS}")
print(f"  Output dim  : 1  (ΔX)")
print(f"  Parameters  : {n_params:,}")
print()

# ---------------------------------------------------------------------------
# 4.  Optimiser and scheduler
# ---------------------------------------------------------------------------
optimiser = torch.optim.Adam(model.parameters(), lr=config.LEARNING_RATE)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimiser, T_max=config.N_EPOCHS, eta_min=1e-5,
)
loss_fn = nn.MSELoss()

# ---------------------------------------------------------------------------
# 5.  Training loop
# ---------------------------------------------------------------------------
print(f"Training for {config.N_EPOCHS} epochs …")
print()

train_losses = []
val_losses   = []
best_val     = float("inf")
best_epoch   = 0

for epoch in range(1, config.N_EPOCHS + 1):

    # --- Training ---
    model.train()
    epoch_train_loss = 0.0
    n_train_batches  = 0

    for X_batch, Y_batch in train_loader:
        X_batch = X_batch.to(device)
        Y_batch = Y_batch.to(device)

        optimiser.zero_grad()
        pred = model(X_batch)
        loss = loss_fn(pred, Y_batch)
        loss.backward()

        # Gradient clipping for stability
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimiser.step()
        epoch_train_loss += loss.item()
        n_train_batches  += 1

    avg_train = epoch_train_loss / n_train_batches

    # --- Validation ---
    model.eval()
    epoch_val_loss = 0.0
    n_val_batches  = 0
    with torch.no_grad():
        for X_batch, Y_batch in val_loader:
            X_batch = X_batch.to(device)
            Y_batch = Y_batch.to(device)
            pred = model(X_batch)
            loss = loss_fn(pred, Y_batch)
            epoch_val_loss += loss.item()
            n_val_batches  += 1

    avg_val = epoch_val_loss / n_val_batches

    train_losses.append(avg_train)
    val_losses.append(avg_val)
    scheduler.step()

    # Save best model
    if avg_val < best_val:
        best_val   = avg_val
        best_epoch = epoch
        torch.save(model.state_dict(),
                   os.path.join(config.MODELS_DIR, "flow_model.pt"))

    # Print every 10 epochs
    if epoch % 10 == 0 or epoch == 1:
        lr_now = scheduler.get_last_lr()[0]
        print(f"  Epoch {epoch:3d}/{config.N_EPOCHS}  "
              f"train_MSE={avg_train:.6f}  val_MSE={avg_val:.6f}  "
              f"lr={lr_now:.6f}")

print()
print(f"  Best model at epoch {best_epoch}  val_MSE={best_val:.6f}")
print()

# Reload best model weights
model.load_state_dict(
    torch.load(os.path.join(config.MODELS_DIR, "flow_model.pt"),
               map_location=device)
)
model.eval()

# ---------------------------------------------------------------------------
# 6.  Plot: training and validation loss
# ---------------------------------------------------------------------------
print("Generating training_loss.png …")

fig, (ax_l, ax_r) = utils.make_fig(nrows=1, ncols=2, figsize=(14, 5))

epochs_arr = np.arange(1, config.N_EPOCHS + 1)
ax_l.plot(epochs_arr, train_losses, "b-", lw=1.5, label="Train MSE")
ax_l.plot(epochs_arr, val_losses,   "r-", lw=1.5, label="Val MSE")
ax_l.axvline(best_epoch, color="green", ls="--", lw=1,
             label=f"Best epoch={best_epoch}")
ax_l.set_xlabel("Epoch", fontsize=12)
ax_l.set_ylabel("MSE loss", fontsize=12)
ax_l.set_title("Training curve (linear scale)", fontsize=10)
ax_l.legend(fontsize=9)

ax_r.semilogy(epochs_arr, train_losses, "b-", lw=1.5, label="Train MSE")
ax_r.semilogy(epochs_arr, val_losses,   "r-", lw=1.5, label="Val MSE")
ax_r.axvline(best_epoch, color="green", ls="--", lw=1)
ax_r.set_xlabel("Epoch", fontsize=12)
ax_r.set_ylabel("MSE loss (log scale)", fontsize=12)
ax_r.set_title("Training curve (log scale)", fontsize=10)
ax_r.legend(fontsize=9)

fig.suptitle(
    f"G(x,z) → ΔX Training  ({n_params:,} parameters)\n"
    f"Best val_MSE={best_val:.6f} at epoch {best_epoch}",
    fontsize=12, y=1.01,
)
fig.tight_layout()
utils.save_fig(fig, os.path.join(config.PLOTS_DIR, "training_loss.png"))

# ---------------------------------------------------------------------------
# 7.  Plot: prediction examples at different x values
# ---------------------------------------------------------------------------
print("Generating prediction_examples.png …")

x_test_vals = [0.3, 1.0, 1.5, 3.0, 5.5]
n_test      = 2000
z_test      = torch.linspace(-3, 3, n_test).unsqueeze(1)

fig2, axes2 = utils.make_fig(nrows=1, ncols=len(x_test_vals),
                              figsize=(4*len(x_test_vals), 5))

for ax, x_val in zip(axes2, x_test_vals):
    # Build input tensor
    x_in  = torch.full((n_test, 1), x_val / config.DOMAIN_HI)
    x_in_cat = torch.cat([x_in, z_test], dim=1).to(device)

    with torch.no_grad():
        dx_pred = model(x_in_cat).cpu().numpy().ravel()

    z_np = z_test.numpy().ravel()

    # Scatter plot: z vs predicted ΔX
    ax.plot(z_np, dx_pred, "b-", lw=1.5, label="G(x,z)")

    # Overlay linear approximation: μ(x) + σ(x)·z
    # Find training labels near this x
    near_mask = np.abs(x_t - x_val) < 0.3
    if near_mask.sum() > 10:
        mu_local  = dx[near_mask].mean()
        sig_local = dx[near_mask].std()
        ax.plot(z_np, mu_local + sig_local * z_np, "r--", lw=1.5,
                label=f"Linear μ+σz")
        ax.axhline(mu_local, color="gray", ls=":", lw=0.8)

    ax.set_xlabel("Latent z", fontsize=9)
    ax.set_ylabel("ΔX", fontsize=9)
    ax.set_title(f"x = {x_val}", fontsize=10)
    ax.set_xlim(-3, 3)
    if ax == axes2[0]:
        ax.legend(fontsize=7)

fig2.suptitle(
    "Predicted ΔX vs latent z at different SDE positions\n"
    "Blue=network, Red=linear approx. Non-linearity near walls is the boundary effect.",
    fontsize=11, y=1.01,
)
fig2.tight_layout()
utils.save_fig(fig2, os.path.join(config.PLOTS_DIR, "prediction_examples.png"))

# ---------------------------------------------------------------------------
# 8.  Diagnostics
# ---------------------------------------------------------------------------
print()
print("=" * 60)
print("DIAGNOSTICS")
print("=" * 60)
print()
print(f"  Training samples  : {n_train:,}")
print(f"  Validation samples: {n_val:,}")
print(f"  Network parameters: {n_params:,}")
print(f"  Best val MSE      : {best_val:.6f}")
print(f"  Best epoch        : {best_epoch}")
print()
print(f"  MSE interpretation:")
print(f"    True ΔX variance  : {np.var(dx):.6f}")
print(f"    Best val MSE      : {best_val:.6f}")
print(f"    Relative MSE      : {best_val/np.var(dx):.4f}")
print(f"    (Relative < 0.01 = excellent; < 0.1 = good)")
print()

# Quick prediction test
model.eval()
with torch.no_grad():
    x_demo = torch.tensor([[1.5 / config.DOMAIN_HI, 0.0]]).to(device)
    dx_demo = model(x_demo).cpu().item()
print(f"  Sample prediction:  G(x=1.5, z=0) = {dx_demo:.6f}")
print(f"  Expected (≈μ(1.5)): {dx[np.abs(x_t-1.5)<0.3].mean():.6f}")
print()
print("FILES WRITTEN")
print("  models/flow_model.pt")
print("  plots/training_loss.png")
print("  plots/prediction_examples.png")
print()
print("WHAT TO CHECK IN THE PLOTS")
print()
print("  training_loss.png:")
print("    Train and val curves should track closely (no overfitting).")
print("    Val loss should decrease monotonically and plateau.")
print("    If val rises while train falls → reduce model size or add dropout.")
print()
print("  prediction_examples.png:")
print("    For interior x (e.g. x=3.0): G(x,z) ≈ σ·z (nearly linear, zero bias).")
print("    For x near left wall (x=0.3): G(x,z) should be right-shifted")
print("    (positive bias, and the curve deviates from the red linear approx).")
print("    For x near right wall (x=5.5): G(x,z) should be left-shifted.")
print("    These deviations are the BOUNDARY CORRECTIONS the network learned.")
print()
print("Done.  Run 08_rollout.py next.")
